[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "b17a9b401916b8f5f285705f3173e0459fda35c4"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "443d07097d8f898e3ac7e3fde473c0f5941b65aab5652f49ae5b20690fd54a86"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.i686-linux-musl.tar.gz"
[[ThriftJuliaCompiler]]
arch = "aarch64"
git-tree-sha1 = "f8b16255d3ffcb1f6931ec52829bf7148f3b40e1"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "f3a9bf5f800728ee2ffebbfc543c7a8c85bf049a58a2db990241df6c4829d698"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.aarch64-linux-musl.tar.gz"
[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "69d92e90ac3b20231c4a7fefcf9f6f9f60dcb133"
os = "windows"

    [[ThriftJuliaCompiler.download]]
    sha256 = "ed38953d26bc2edc38f2371ef45a5ba8e334fa8980d831d94e93855951e2293b"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.i686-w64-mingw32.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "f48cdaaef4278109d7666aeaecc54253847272b6"
os = "windows"

    [[ThriftJuliaCompiler.download]]
    sha256 = "5d44a383ea063ae3f5eed916f8ecbb8b4b548b0ceb8670580977ed81abfd02c0"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.x86_64-w64-mingw32.tar.gz"
[[ThriftJuliaCompiler]]
arch = "armv7l"
git-tree-sha1 = "6de6a43cfef0b4cd01f4b8d635f77b3bd5f96733"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "fcf1a60b0377440ba3ef8c045cc2419097ff659af596f01bc7d527fee01ffe1f"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.armv7l-linux-gnueabihf.tar.gz"
[[ThriftJuliaCompiler]]
arch = "armv7l"
git-tree-sha1 = "be06725516e34bf869133c91c1653baff95d6edb"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "872ae45446da3ac35ac250d914446b7c1df60c8929cecfff8f37e4523e368127"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.armv7l-linux-musleabihf.tar.gz"
[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "eb31b9a1a38398303041e3b1363f445ea1ab62a7"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "1bbde27fc0e9767d63c4ce1441363c3718ce3b1cbc0479bb15c6b858acbaed3c"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.i686-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "ad16ac53cf5522ff590abe30aaded1c241e2f764"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "ea128a49e750bf6866a530187dae5bcfffd64bd511135c84fb639959776e6210"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.x86_64-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "powerpc64le"
git-tree-sha1 = "65d6c03458d3b785e580e5c90d123f2fa63badae"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "db41b87bfdd6cd642607a8b12aecffe91b7d19e011adfc615db9fbf632318b4d"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.powerpc64le-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "f47d6011dd2b1f9e5b47335b4e0ab7852a566549"
os = "macos"

    [[ThriftJuliaCompiler.download]]
    sha256 = "65873682a581748342b75352ee3897cf600f38777168e9fa5b574a9d660036f3"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.x86_64-apple-darwin14.tar.gz"
[[ThriftJuliaCompiler]]
arch = "aarch64"
git-tree-sha1 = "95fa0ec6e1c7e28f85edc2483d6a5cce095f0891"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "12aa39a31ec77f4307719b0354d6c0ce951cef8f8e1ed601f528a6e0cd96e8b5"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.aarch64-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "74491bd70b7a48feb5cfa4754979c722badffaf0"
os = "freebsd"

    [[ThriftJuliaCompiler.download]]
    sha256 = "31c1b7f0b5ba6b5eb29651f672ea666a4e3da84efc5075144a883c2ee576b94b"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.x86_64-unknown-freebsd11.1.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "0e4f0b01b2ed6156cd822e131f873b29ee9080eb"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "76d4d53ea01e04371c9b9e58253399935fa366da14a97330c983be63d4f4867c"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.11.0+0/ThriftJuliaCompiler.v0.11.0.x86_64-linux-musl.tar.gz"
