[[ThriftJuliaCompiler]]
arch = "aarch64"
git-tree-sha1 = "209c4df046b8de77e2a538c8416540bc8e155eb1"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "82770ff5f1071cd4d6217b9edf936e07795fb50266dbe5e8a80c5d2115d722c6"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.aarch64-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "aarch64"
git-tree-sha1 = "6532927c209b1589ca26ff05a0485c21711541d4"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "2467b08f52f876f1dae8583b7db36adad5ae8333f540daba5b3cf739be477c4b"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.aarch64-linux-musl.tar.gz"
[[ThriftJuliaCompiler]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "37d602d53da9bf259248b8c24b617d80a0bc0e7e"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "458eb05662a38f95c5375ad96aab65d20b7053d6e3c897dcc192ed87fb934047"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.armv7l-linux-gnueabihf.tar.gz"
[[ThriftJuliaCompiler]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bb0410e53ff4bb66b59894b0443e6f897dc895b1"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "1c69eead9a11bacfd4ed0ccd118158cc938506bb36d710735e2fcce6345f4aa0"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.armv7l-linux-musleabihf.tar.gz"
[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "5ba5fd76768821b3fcd6fc2f39e7912b3c300708"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "947c01a60e064f9ead624b7d7e4611b1c1fe4fe756ca700da21fd9ead2468456"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.i686-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "83c8faa15d26eca676c6ec80d9d3482c793a6f6b"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "6f8bf6a70fe2376a4599ca723b9897286b25bf482670bff48b34b755c6232270"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.i686-linux-musl.tar.gz"
[[ThriftJuliaCompiler]]
arch = "i686"
git-tree-sha1 = "80693867e561a0a9ffe97cdda9ab38653aa4b4a7"
os = "windows"

    [[ThriftJuliaCompiler.download]]
    sha256 = "8c3be693a9f9ce6a5438b65eccc9e8aa51ddcb0f158eece23f65e8f5e748d91f"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.i686-w64-mingw32.tar.gz"
[[ThriftJuliaCompiler]]
arch = "powerpc64le"
git-tree-sha1 = "bf1cba871efbb6454e7506fcd2d17b98ddd59a35"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "ab14d2a189f94fdec5872adbf1ceab6cdf9cfa2d737814e6041cae853ed33b9f"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.powerpc64le-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "22225ffe5699cf16359794519a68854dd4bfa732"
os = "macos"

    [[ThriftJuliaCompiler.download]]
    sha256 = "b07ebf08d9cc46dcfef1730736cb30edda148c78f0bc516ae9bcf5607903671f"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.x86_64-apple-darwin.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "baa96bb3f705f3e0d47c37390ee168b9eb62600f"
libc = "glibc"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "27eaf5b93c14308231df4263ddf169b1345a2af6be474ebe8f619c0c10796840"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.x86_64-linux-gnu.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "556139d6b3820d6aa87b227e7226b9ea1e4f9b0b"
libc = "musl"
os = "linux"

    [[ThriftJuliaCompiler.download]]
    sha256 = "0a1a55687d1905dd3e0e27a3448b3aade97239d07673cfa9326a69b7cc756453"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.x86_64-linux-musl.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "21b1cfebddc3dec6a1fccea193083ccbfb0bafa8"
os = "freebsd"

    [[ThriftJuliaCompiler.download]]
    sha256 = "b98eeeba6daa2f5e15c1ed1d2c66cac37c06339ce48afe78e0d54c9d86b3150f"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.x86_64-unknown-freebsd.tar.gz"
[[ThriftJuliaCompiler]]
arch = "x86_64"
git-tree-sha1 = "2ec34e0ce59befe5f7a8f1a7afb3ead2a12236d7"
os = "windows"

    [[ThriftJuliaCompiler.download]]
    sha256 = "c978be7befa6a2e727211653b5595884b1d5bb3b46d4eb2f090f715227a82a90"
    url = "https://github.com/JuliaBinaryWrappers/ThriftJuliaCompiler_jll.jl/releases/download/ThriftJuliaCompiler-v0.12.0+0/ThriftJuliaCompiler.v0.12.0.x86_64-w64-mingw32.tar.gz"
